name: Rakit APK Cordova Otomatis
on:
  workflow_dispatch: # Memunculkan tombol klik manual di HP

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Ambil Kode dari Repo
      uses: actions/checkout@v4

    - name: 2. Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 3. Set Up Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: 4. Set Up Android SDK Studio
      uses: android-actions/setup-android@v3

    - name: 5. Proses Instalasi Cordova & Plugin Anti-Tidur
      run: |
        npm install -g cordova
        
        # Buat proyek Cordova di folder luar agar tidak bentrok
        cd ..
        cordova create direktori_apk com.zakka.otppanel PanelOTP
        cd direktori_apk
        
        cordova platform add android
        
        cordova plugin add cordova-plugin-background-mode
        cordova plugin add cordova-plugin-local-notification
        
        # Hapus file bawaan Cordova, ganti dengan file HTML/JS Anda dari GitHub
        rm -rf www/*
        cp -r $GITHUB_WORKSPACE/* www/
        
        # Mulai merakit menjadi APK Android
        cordova build android --debug

        # Pindahkan hasil APK ke folder awal agar bisa di-download
        cp platforms/android/app/build/outputs/apk/debug/app-debug.apk $GITHUB_WORKSPACE/PanelOTP-AntiTidur.apk

    - name: 6. Kirim APK ke Halaman Download
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Panel-OTP-Matang
        path: PanelOTP-AntiTidur.apk
